bankproject/Bankapp/urls.py
from . import views
from django.urls import path
app_name='Bankapp'
urlpatterns=[
    path('',views.home,name="home"),
    path('branch/<int:b_id>/', views.detail, name="detail"),
    path('kalpeta',views.kalpeta,name="kalpeta"),
    path('mananthvady',views.mananthvady,name="mananthvady"),
    path('bathery',views.bathery,name="bathery"),
    path('koduvally',views.koduvally,name="koduvally"),
    path('tmsry',views.tmsry,name="tmsry"),
    path('medc',views.medc,name="medc"),
    path('kaloor',views.kaloor,name="kaloor"),
    path('aluva',views.aluva,name="aluva"),
    path('kakkanad',views.kakkanad,name="kakkanad"),
]

bankproject/applications/urls.py
from django.urls import path
from . import views
app_name='applications'
urlpatterns = [
    path('',views.create,name="create"),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),  # AJAX

]

bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Bankapp.urls")),
    path('register/',include("register.urls")),
    path('applications/',include("applications.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_url=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankproject/register/urls.py
from django.urls import path
from . import views
app_name='register'
urlpatterns = [
    path('register',views.register,name="register"),
    path('login',views.login,name='login'),
    path('logout',views.logout,name="logout"),
    ]

bankproject/applications/models.py
from django.db import models
from datetime import date
# Create your models here.
from django.urls import reverse


class District(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    img= models.ImageField(upload_to='pics')

    def get_url(self):
        return reverse('Bankapp:detail',args=[self.id])

    def __str__(self):
        return self.name


class Application(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'), ('Female', 'Female'),)
    Accounts = (
            ('SavingsAccount', 'SavingsAccount'), ('SalaryAccount', 'SalaryAccount'), ('CreditAccount', 'CreditAccount'),)
    name=models.CharField(max_length=100)
    age=models.CharField(max_length=10)
    birth_date=models.DateField()
    mobile=models.CharField(max_length=25)
    email=models.EmailField(max_length=150)
    address=models.TextField()
    gender=models.CharField(max_length=10,choices=GENDER_CHOICES,default=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True)
    m_name = models.CharField(max_length=100,default=True)
    acc_type=models.CharField(choices=Accounts,max_length=100,default=True)

    def __str__(self):
        return self.name

bankproject/register/models.py
from django.db import models

# Create your models here.

bankproject/applications/forms.py
from django import forms
from .models import Application, Branch

materials = (
    ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Checkbook', 'Checkbook'),)
class ApplicationForm(forms.ModelForm):
    m_name=forms.MultipleChoiceField(choices=materials,label="materials Required",widget=forms.CheckboxSelectMultiple(attrs={'class':'form-group'}))
    class Meta:
        model = Application
        fields = ['name','age','birth_date','mobile','email','address','gender','district','branch','m_name','acc_type']
        labels ={'name':'FullName','age':'Age','birth_date':'DateofBirth','mobile':'Mobile Number','address':'Address',
                 'gender':'Gender','district':'District','branch':'Branch','m_name':'Materials Required','acc_type':'Account Type'}
        attrs=({'district':{'class':'form-control'}})
        widgets=({
            'gender':forms.RadioSelect,
            'acc_type':forms.Select,
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'age':forms.NumberInput(attrs={'class':'form-control'}),
            'birth_date':forms.DateInput(attrs={'class':'form-control'},format="%d/%m/%Y"),
            'mobile':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'address':forms.Textarea(attrs={'class':'form-control'}),
            'acc_type':forms.Select(attrs={'class':'form-control'}),
            'district':forms.Select(attrs={'class':'form-control'}),
            'branch':forms.Select(attrs={'class':'form-control'}),
        })

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branch.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

bankproject/applications/views.py
from django.shortcuts import render, redirect
from .forms import ApplicationForm
from .models import Application, Branch, District


# Create your views here.
def create(request):
    form = ApplicationForm
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
        return redirect('/')
    return render(request, "application.html",{'form':form})


def load_branches(request):
    district_id = request.GET.get('district_id')
    branches = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'branches.html', {'branches': branches})
    # return JsonResponse(list(branches.values('id', 'name')), safe=False)

bankproject/register/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def register(request):
    if request.method=="POST":
        firstname=request.POST['firstname']
        lastname=request.POST['lastname']
        email=request.POST['email']
        username=request.POST['username']
        password=request.POST['password']
        cpassword=request.POST['cpassword']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"User exists")
                print("user exists")
                return redirect('register:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"Email Exists")
                print("email exists")
                return redirect('register:register')
            else:
                user=User.objects.create_user(username=username,password=password,first_name=firstname,last_name=lastname,email=email)
                user.save()
                messages.success(request,"Created")
                print("user created")
                return redirect('register:login')
        else:
            messages.info(request, "password Error")
            print("check password")
            return redirect('register:register')
    return render(request,"register.html")

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"invlid username or password")
            return redirect('register:login')
    return render(request,"login.html")

def logout(request):
    auth.logout(request)

    return redirect('/')

bankproject/templates/application.html
{% extends 'base.html' %}

{% block content %}

<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-3">
					<h2 class="heading-section" style="color:darkgreen;font-family: 'Rubik Dirt', 'Cursive';">Employee Form</h2>
				</div>
			</div>
            <div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
                    <form method="POST" id="appForm" enctype="multipart/form-data" data-branches-url="{% url 'applications:ajax_load_branches' %}">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row">
                            <div class="form-group">
                        {{ form.as_p }}
                            </div>
                            <div class="form-group" style="text-align:center;">
                    <button type="submit"class="btn btn-success" value="Submit">Submit</button>
                            <a href="/" type="submit"  class="btn btn-info" >Home</a>
                            </div>
            </form>
                    </div>

            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script>
                $("#id_district").change(function () {
                    const url = $("#appForm").attr("data-branches-url");  // get the url of the `load_cities` view
                    const districtId = $(this).val();  // get the selected country ID from the HTML input

                    $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                        data: {
                            'district_id': districtId       // add the country id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the `load_cities` view function
                            $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server
                            /*

                            let html_data = '<option value="">---------</option>';
                            data.forEach(function (branch) {
                                html_data += `<option value="${branch.id}">${branch.name}</option>`
                            });
                            console.log(html_data);
                            $("#id_branch").html(html_data);

                            */
                        }
                    });

                });
            </script>
                </div>
<!--<script>-->
<!--$(document).ready( function () {-->

<!--   $("input[name='m_name']").each( function () {-->
<!--       alert( $(this).val() );-->
<!--   });-->

<!--});-->
<!--</script>-->
{% endblock %}

bankproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %} {% endblock %} </title>
<title>About us</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Travello template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about.cs' %}s">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about_responsive.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about_responsive.css' %}">
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    </div>
    {% include 'footer.html' %}

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>


<script src="{% static 'js/about.js' %}"></script>
</body>
</html>

bankproject/templates/branches.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

bankproject/templates/branchinfo.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
				<div class="col-md-6 text-center mb-3">
					<h2 class="heading-section" style="color:red;background-color:green;font-family: 'Rubik Dirt', 'Cursive';">{{ br.name }}  Blog</h2>
				</div>
			</div>
    <div class="row">

        <div class="col-md-6">
        <img  src="{{ br.img.url }}" width="400" height ="500"><br>
        </div>
        <div class="col-md-4">
            <h1>{{ br.name }}</h1><br>
            <h1>{{ br.district }}</h1><br>
            <a class="btn btn-success" href="{% url 'Bankapp:home' %}">HOME</a>
        </div>
    </div>
</div>

{% endblock %}


<!--<li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="true">-->
<!--            BRANCHES-->
<!--        </a>-->
<!--          {% for i in branches %}-->
<!--        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->

<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:kalpeta' %}">KALPETTA</a></li>-->
<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:mananthvady' %}">MANANTHAVADY</a></li>-->
<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:bathery' %}">BATHERY</a></li>-->
<!--          <li><hr class="dropdown-divider"></li>-->
<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:koduvally' %}">KODUVALLY</a></li>-->
<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:tmsry' %}">THAMARASSERY</a></li>-->
<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:medc' %}">MED.COLLEGE</a></li>-->
<!--          <li><hr class="dropdown-divider"></li>-->
<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:kaloor' %}">KALOOR</a></li>-->
<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:aluva' %}">ALUVA</a></li>-->
<!--          <li><a class="dropdown-item" href="{% url 'Bankapp:kakkanad' %}">KAKKANAD</a></li>-->
<!--        </ul>-->
<!--          {% endfor %}-->
<!--      </li>-->
<!--&lt;!&ndash;-->

bankproject/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
				<div class="col-md-6 text-center mb-3">
					<h2 class="heading-section" style="color:red;background-color:green;font-family: 'Rubik Dirt', 'Cursive';">{{ br.name }}  Blog</h2>
				</div>
			</div>
    <div class="row">

        <div class="col-md-6">
        <img  src="{{ br.img.url }}" width="400" height ="500"><br>
        </div>
        <div class="col-md-4">
            <h1>{{ br.name }}</h1><br>
            <h1>{{ br.district }}</h1><br>
            <a class="btn btn-success" href="{% url 'Bankapp:home' %}">HOME</a>
        </div>
    </div>
</div>

{% endblock %}

bankproject/templates/footer.html
<div class="footer navbar-footer-bottom my_footer col text-center" style=" height:50px;bottom: 0;width: 100%; margin-top:10%;">
    <p class="text-center" style="color:black; padding-top:20px;font-size:16px;">&copy; issued by The online store pvt Ltd 2022</p>
</div>

bankproject/templates/header.html
{% load static %}
<header class="header">
	<div class="container-fluid" style="background-color:MistyRose;">
		<div class="row">
			<div class="col">
				<div class="header_content d-flex flex-row align-items-center justify-content-center">
					<div class="header_content_inner d-flex flex-row align-items-center justify-content-start">
						<div class="logo"><a href="/" style="color:red;font-size:60px; align-items:center; justify-content: center;">STATE BANK of KERALA</a></div>
							<nav class="main_nav">
								<ul class="d-flex flex-row align-items-start justify-content-start">
								</ul>
							</nav>
					</div>
					</div>
				</div>
			</div>
		</div>
</header>

bankproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body class="img js-fullheight" style="background-image: url({% static 'images/bg.jpg' %});">
<div class="why">
<!--		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/bg.jpg' %}" data-speed="0.8"></div>-->
		<div class="container">
			<div class="row">
				<div class="col text-center">
					<div class="section_subtitle">State Bank of Kerala</div>
					<div class="section_title"><h2>Banking for All</h2></div>
				</div>
			</div>
			<div class="row why_row">


<div class="container">
    <div class="row mx-auto" style="align-items: stretch;
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
  overflow-x: auto;
  overflow-y: hidden;" >
        {% for i in branches %}
        <div class="col-md-3">
            <div class="card" style="margin-bottom:25px;flex-basis: 33.333%; flex-grow: 0;flex-shrink: 0; ">
                 <img class="card-img-top" src="{{i.img.url}}" alt="refresh" width="270" height="300">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text" style="height:57px; overflow:hidden;">{{i.desc}}</p>
                    <a href="{% url 'Bankapp:detail' i.id %}" class="btn btn-primary">Read more</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</body>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

bankproject/templates/klptabranchinfo.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
				<div class="col-md-6 text-center mb-3">
					<h2 class="heading-section" style="color:red;background-color:green;font-family: 'Rubik Dirt', 'Cursive';">{{ br.name }}  Blog</h2>
				</div>
			</div>
    <div class="row">

        <div class="col-md-6">
        <img  src="{{ brs.img.url }}" width="400" height ="500"><br>
        </div>
        <div class="col-md-4">
            <h1>{{ brs.name }}</h1><br>
            <h1>{{ brs.district }}</h1><br>
            <a class="btn btn-success" href="{% url 'Bankapp:home' %}">HOME</a>
        </div>
    </div>
</div>

{% endblock %}

bankproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<body class="img js-fullheight" style="background-image: url({% static 'images/bg.jpg' %});">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section" style="color:darkgreen;font-family: 'Rubik Dirt', 'Cursive';">LOGIN</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
<!--		      	<h3 class="mb-4 text-center">Have an account?</h3>-->
		      	<form action="login" method="post" class="signin-form">
					{% csrf_token %}
		      		<div class="form-group">
		      			<input type="text" name="username" class="form-control" placeholder="Username" required>
		      		</div>
	            <div class="form-group">
	              <input id="password-field" type="password" name="password" class="form-control" placeholder="Password" required>
<!--					<span toggle="#password-field" style="align:right;" class="fa fa-fw fa-eye field-icon toggle-password"></span>-->
	            </div>
	         <div class="form-group" style="text-align:center;">
					<button class="btn btn-success" type="submit">Login</button>
					<a href="/" type="submit"  class="btn btn-info" >Home</a>
<!--	            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>-->
	            </div>
<!--	            <div class="form-group d-md-flex">-->
<!--	            	<div class="w-50">-->
<!--		            	<label class="checkbox-wrap checkbox-primary">Remember Me-->
<!--									  <input type="checkbox" checked>-->
<!--									  <span class="checkmark"></span>-->
<!--									</label>-->
<!--								</div>-->
<!--								<div class="w-50 text-md-right">-->
<!--									<a href="#" style="color: #fff">Forgot Password</a>-->
<!--								</div>-->
<!--	            </div>-->
	          </form>
						{% for msg in messages %}
						<h5 style="color:red; background-color:black; text-align:center;">{{msg}}</h5>
						{% endfor %}
		      </div>
              </div>
			</div>
		</div>

	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

{% endblock %}

bankproject/templates/navbar.html
{% load static %}
<div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-top:150px;">
  <a class="navbar-brand" href="/">HOME</a>
  {% if user.is_authenticated %}
  <h3 class="navbar-brand" style="color:yellow;">hello, {{user.username}}</h3>
  <a class="navbar-brand" href="{% url 'applications:create' %}">APPLICATION FORM</a>
  <a class="navbar-brand" href="{% url 'register:logout' %}">LOGOUT</a>
  {% else %}
    <a class="navbar-brand" href="{% url 'register:register' %}">REGISTER</a>
    <a class="navbar-brand" href="{% url 'register:login' %}">LOGIN</a>
  {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <li class="nav-item dropdown {% if 'applications' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          BRANCHES
        </a>
            <div>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for cat in links %}
                <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a>
            {% endfor %}
            </div>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
  </div>

bankproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body class="img js-fullheight" style="background-image: url({% static 'images/bg.jpg' %});">
<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-3">
					<h2 class="heading-section" style="color:darkgreen;font-family: 'Rubik Dirt', 'Cursive';">REGISTER HERE</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	<form action="" method="post" class="signin-form">
					{% csrf_token %}
					<div class="form-group">
		      			<input type="text" name="firstname" class="form-control" placeholder="Firstname" required>
		      		</div>
					<div class="form-group">
		      			<input type="text" name="lastname" class="form-control" placeholder="Lastname" required>
		      		</div>
					<div class="form-group">
		      			<input type="email" name="email" class="form-control" placeholder="Email ID" required>
		      		</div>
					<div class="form-group">
		      			<input type="text" name="username" class="form-control" placeholder="Username" required>
		      		</div>
					<div class="form-group">
		      			<input type="password" name="password" class="form-control" placeholder="Enter Password" required>
		      		</div>
					<div class="form-group">
		      			<input type="password" name="cpassword" class="form-control" placeholder="Confirm Password" required>
		      		</div>
	            <div class="form-group" style="text-align:center;">
					<button class="btn btn-success" type="submit">REGISTER</button>
					<a href="/" type="submit"  class="btn btn-info" >Home</a>
<!--	            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>-->
	            </div>
	          </form>
						{% for msg in messages %}
						<h5 style="color:red; background-color:black; text-align:center;">{{msg}}</h5>
						{% endfor %}
                    </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
    {% endblock %}